name: Convert Markdown to PDF using md-to-pdf

on: 
  push:
    paths:
      - 'docs/README.md'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install md-to-pdf
        run: |
          npm install -g md-to-pdf

      - name: Convert Markdown to PDF
        run: |
          md-to-pdf docs/README.md 

      - name: Commit and push
        run: |
          git config --local user.email "121922274+Shintaro-Abe@users.noreply.github.com"
          git config --local user.name "Shintaro Abe"
          git add README.pdf
          git commit -m "Update README.pdf"
          git push
